version: '3.2'
services:
  truckx_postgres:
    image: postgres:latest
    container_name: truckx_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    networks:
      - truckx_network

  truckx_app:
    container_name: truckx_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - truckx_postgres
    networks:
      - truckx_network

  truckx_postgres_explorer:
    image: dpage/pgadmin4
    container_name: truckx_postgres_explorer
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EXPLORER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_EXPLORER_PASSWORD}
    depends_on:
      - truckx_postgres
    ports:
      - "5050:80"
    networks:
      - truckx_network
    restart: unless-stopped

networks:
  truckx_network:
    driver: bridge
